SELECT CITY, LENGTH(CITY)
FROM STATION
WHERE CITY IN (
    SELECT CITY FROM (
        SELECT CITY FROM STATION 
        WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
        ORDER BY CITY
    ) WHERE ROWNUM = 1
)
OR CITY IN (
    SELECT CITY FROM (
        SELECT CITY FROM STATION 
        WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
        ORDER BY CITY
    ) WHERE ROWNUM = 1
);
